

export const APP_LOAD = 'APP_LOAD';
export const APP_LOAD_DONE = 'APP_LOAD_DONE';
export const LIKE_ART = "LIKE_ART";
export const DISLIKE_ART = "DISLIKE_ART";
export const ART_GALLERY_DATA = 'ART_GALLERY_DATA';
export const FILTER_ART_GALLERY = 'FILTER_ART_GALLERY';
export const WHISH_LIST_LS_NAME = "WHISH_LIST_LS_NAME";
export const FETCH_LSTEST_ART_GALLERY = "FETCH_LSTEST_ART_GALLERY";
export const UPDATE_LSTEST_ART_GALLERY = "UPDATE_LSTEST_ART_GALLERY";
