import { Footer } from '@/components/Footer'
import { Navigation } from '@/components/Navigation'
import NoResultFound from '@/components/NoResultFound'
import { store } from '@/store/store'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import styles from '@/styles/Home.module.css'
import { fetchListByIds } from '@/api'
import CardComponent from '@/components/CardComponent'

export const WishList = () => {
    const storeData = useSelector((state) => state.whishList);
    const [wishListData, setWishListData] = useState(() => [])

    const fetchData = async () => {
        if (storeData && storeData.length > 0) {
            let res = await fetchListByIds(storeData);
            setWishListData(prevState => res.data)
        } else {
            setWishListData(prevState => [])
        }
    }

    useEffect(() => {
        fetchData();
    }, [storeData])

    return (
        <>
            <Head>
                <title>whishList page </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Navigation></Navigation>
                {wishListData && wishListData.length > 0 ? <div className='mx-auto max-w-7xl px-6 lg:px-8 mt-24 mb-24'>
                    <div className='grid grid-cols-3 gap-4 content-start'>
                        {wishListData?.map((item) => <React.Fragment key={item.id}>  <CardComponent data={item}></CardComponent>  </React.Fragment>)}
                    </div>
                </div> : <NoResultFound></NoResultFound>}
                <Footer></Footer>
            </main>
        </>

    )
}


export default WishList;